### ISSUE TITLE
Skeletons of Functions

### ISSUE THREAD

**Issue by Radascript** [UBC-MDS/tweetRpoll#3]
In the tweetRpoll.r file, define and document the functions

For this milestone you will write R function documentation that will serve as specifications, but you will NOT write any code for your package functions. Specifically, set-up empty functions (with appropriate function names) containing no code in the files where you will eventually write code. Write function documentation (e.g., complete roxygen2 comments). These are the functions you wrote about in your proposal.

**Comment by xiangwxt** [comment]
Nice done.
